name: meg-m1-ue5-unix2
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest prioriy
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python>=3.8
  - jupyterlab>=3
  - pip
  - nbresuse
  - nodejs
  - fastqc
  - fastp
  - hisat2    
  - samtools
  - trimmomatic
  - fastp
  - star
  - pip:
    - bash_kernel
