name: meg-m1-ue5-unix
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest priority
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  # Jupyter dependencies
  - jupyterhub>=1.5,<2
  - jupyterlab>=3.2,<4
  - jupyter-resource-usage
  - jupyterlab-topbar
  - jupyterlab-topbar-text
  - jupyterlab-system-monitor
  - nodejs
  # Jupyter archive
  # https://github.com/jupyterlab-contrib/jupyter-archive
  - jupyter-archive=3.3.4
  # RNA-seq tools
  - fastqc
  - fastp
  - hisat2    
  - samtools
  - trimmomatic
  - star
  - multiqc
  # Bash environment
  - python>=3.8
  - pip
  - pip:
    - bash_kernel
